database:
  relational:
    host: localhost
    port: 5432
    database-name: dialog
    auth:
      user: postgres
      password: postgres

sql:
  templates:
    path: ./db/sql/**/*.sql

server:
  port: 8080
  debug: true

api:
  jwt:
    secret: i9Da62Q1TP5I4Y7v7Ksi8XzZZGqM3JBoBjBcscweUFR5iGJGUe6t8x0XE33KoK8cfV80rCenyAsuXJ8qYZR3nRznN8GkK4ZSANsbUjmnTI6EjjrpN1kiAvqmpL5iKub0
    expires-in: 3h
