database:
  relational:
    host:
    port:
    database-name:
    auth:
      user:
      password:
  redis:
    address: localhost:6379
    password:
    db: 0

sql:
  templates:
    path: ./db/sql/**/*.sql

server:
  port: 8080
  debug: true

api:
  jwt:
    secret:
    expires-in: 3h
